name: GitHub Actions Demo

# 觸發此 action 的時機
on:
  push:
    branches:  # 只要有任何一個 commit 被 push，就會觸發此 action
      - "master"
  pull_request:
    branches:  ["master"]

# 預先定義此 action 要幹嘛
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "? The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "? This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "? The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "? The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "? The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "? This job's status is ${{ job.status }}."
